project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=0d57ca6751d9
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] db version v3.6.23
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] allocator: tcmalloc
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] modules: none
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] build environment:
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten]     distarch: x86_64
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten]     target_arch: x86_64
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I STORAGE  [initandlisten] 
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I STORAGE  [initandlisten] error creating journal dir /data/db/journal boost::filesystem::create_directory: No space left on device: "/data/db/journal"
project-item-db-1  | 2023-10-12T07:17:58.444+0000 I STORAGE  [initandlisten] exception in initAndListen std::exception: boost::filesystem::create_directory: No space left on device: "/data/db/journal", terminating
project-item-db-1  | 2023-10-12T07:17:58.445+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
project-item-db-1  | 2023-10-12T07:17:58.445+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
project-item-db-1  | 2023-10-12T07:17:58.445+0000 I CONTROL  [initandlisten] now exiting
project-item-db-1  | 2023-10-12T07:17:58.445+0000 I CONTROL  [initandlisten] shutting down with code:100
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_18_25_971Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_18_35_293Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_18_40_306Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_19_02_848Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_19_25_088Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_19_46_938Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_20_09_166Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_20_26_986Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_20_49_269Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_21_11_137Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_21_33_510Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_21_55_425Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_22_17_242Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
project-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
project-item-app-1  |           throw err
project-item-app-1  |           ^
project-item-app-1  | 
project-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |   name: 'MongoError'
project-item-app-1  | }]
project-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |     at Pool.emit (events.js:400:28)
project-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |     at Object.onceWrapper (events.js:520:26)
project-item-app-1  |     at Connection.emit ...
project-item-app-1  |     at /app/app.js:24:10
project-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
project-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
project-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
project-item-app-1  |   generatedMessage: true,
project-item-app-1  |   code: 'ERR_ASSERTION',
project-item-app-1  |   actual: null,
project-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 36.86.63.182:27017
project-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
project-item-app-1  |     name: 'MongoError'
project-item-app-1  |   }]
project-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
project-item-app-1  |       at Pool.emit (events.js:400:28)
project-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Connection.emit (events.js:400:28)
project-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
project-item-app-1  |       at Object.onceWrapper (events.js:520:26)
project-item-app-1  |       at Socket.emit (events.js:400:28)
project-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
project-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
project-item-app-1  |   operator: '=='
project-item-app-1  | }
project-item-app-1  | npm ERR! code ELIFECYCLE
project-item-app-1  | npm ERR! errno 1
project-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
project-item-app-1  | npm ERR! Exit status 1
project-item-app-1  | npm ERR! 
project-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
project-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
project-item-app-1  | 
project-item-app-1  | npm ERR! A complete log of this run can be found in:
project-item-app-1  | npm ERR!     /root/.npm/_logs/2023-10-12T07_22_39_637Z-debug.log
project-item-app-1  | 
project-item-app-1  | > docker-software-delivery@1.0.0 start /app
project-item-app-1  | > node ./bin/www
project-item-app-1  | 
project-item-app-1  | NODE_ENV: production
